ARG KANBAN_IMAGE
FROM docker:29-cli AS docker_cli
FROM ${KANBAN_IMAGE}
ARG KANBAN_IMAGE
USER root
COPY --from=docker_cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker_cli /usr/local/libexec/docker/cli-plugins/docker-compose /usr/local/libexec/docker/cli-plugins/docker-compose
COPY installer installer
ENV KANBAN_RUNTIME_IMAGE=${KANBAN_IMAGE}
HEALTHCHECK NONE
ENTRYPOINT ["python", "-m", "installer.quickstart"]
CMD []
